### ISSUE TITLE
You guys should figure out what engine you want this running on before anyone starts coding

### ISSUE THREAD

**Issue by FieryXJoe** [XBHSCS15/battleship#12]
Just using JFrame would be severely limiting for this project, would basically eliminate the ability to have a custom looking user interface, or animations and would make networking more complex. It is probably best for a game engine/library to be chosen before any code gets done as the entire main class would have to be built around it. This decision would be mostly on the GUI guys as they are the ones who would have to deal with it. I already have experience with OpenGl so if you go with that I could definitely be helpful with that. With whatever Engine/Library you go with I should be able to help with the lower level setup, making the basics of rendering, texturing, and animation if necessary and leave the GUI guys to deal with the event based programming, and actual design.

**Comment by abyrne55** [comment]
OpenGL may be overkill. I agree that just JFrame would be too limiting. See #11 for my idea for a graphics library. The @XBHSCS15/graphical-user-interface Team would certainly appreciate your help though.

**Comment by abyrne55** [comment]
Closing due to our seemingly *de facto* choice of Processing
