### ISSUE TITLE
My battleship src folder is now missing?

### ISSUE THREAD

**Issue by apprehensivemeerkat** [XBHSCS15/battleship#14]
Yeah, dunno why this is so. I don't have access to any files through NetBeans now. I can still see everything fine in GitHub (both online Git and local Git).

**Comment by TLounsbury** [comment]
I use a Mac but i can try to help. So do you have the git application and Netbeans open?

**Comment by TLounsbury** [comment]
Change your branch on the desktop app to the master and see if that brings
back the Files.

**Comment by abyrne55** [comment]
What's the status of this issue?

--
Anthony Byrne
Social Media Manager
Boston Granite Exchange
W: (508) 521-1800 | M: (339) 236-1921

**Comment by TLounsbury** [comment]
Unknown. The Meerkat has gone AFK

**Comment by apprehensivemeerkat** [comment]
I'll just fix it in class or something.
