### ISSUE TITLE
What order do I merge in?

### ISSUE THREAD

**Issue by apprehensivemeerkat** [XBHSCS15/battleship#16]
If I want to add Mohak's code to my branch, so I can have access to the Move class, is it
GameLogic -> player-moves
or
player-moves -> GameLogic

**Comment by apprehensivemeerkat** [comment]
My branch is player-moves and Mohak's is GameLogic

**Comment by abyrne55** [comment]
GameLogic -> player-moves

**Comment by apprehensivemeerkat** [comment]
Thanks

**Comment by abyrne55** [comment]
Did it work? I don't see your merge in the branching diagram

**Comment by apprehensivemeerkat** [comment]
I just added it, encountered one issue but fixed it. Can you see if it's there now?

**Comment by abyrne55** [comment]
Not yet. Try committing and syncing

**Comment by mohaksaxena** [comment]
I still see two different branches. Can we both work on the same branch but different classes at the same time?

**Comment by apprehensivemeerkat** [comment]
I want to keep two separate branches, so we can work individually still. The merge thing was just to add your code to mine, not necessarily vice versa.

I committed and synced the changes. I'm even seeing "Merging GameLogic into player-moves …
apprehensivemeerkat authored 5 minutes ago" in the commit log.

**Comment by abyrne55** [comment]
When you "merge branches," you don't combine them into one. You just basically copy the first branch's changes onto the second branch. See the [branching diagram](https://github.com/XBHSCS15/battleship/network) for a graphical representation of what I mean. 

Yes, you can both work on different classes in the same branch.

**Comment by apprehensivemeerkat** [comment]
Byrne, is it still not showing? At least for me, I can see the arrow on the diagram pointing in from GameLogic to player-moves

**Comment by abyrne55** [comment]
I see it. You're good

**Comment by apprehensivemeerkat** [comment]
Cool Beans
NetBeans

(this is my new catch phrase, get used to it)
