### ISSUE TITLE
Activating and then deactivating a tile removes the opacity

### ISSUE THREAD

**Issue by FieryXJoe** [XBHSCS15/battleship#34]
This issue is probably contained within the drawElement() function of GridElement. I couldn't find it at a glance but it shouldn't be too complex unless it is an issue with the processing library. The simplest explanation I can think of for this is that we aren't erasing and redrawing the square but adding one .5 opacity layer on top of another leading to .5 opacity after the first draw .75 after the second .875 after the third etc

**Comment by abyrne55** [comment]
Just for record keeping purposes, this issue was fixed in commit cd7f3be4423f137a124c092d90756ab722aeb4b9
